version: '3.8'

services:
  backend:
    build: ./server
    ports:
      -4001:4001

  frontend:
    build: ./spa
    ports: 
     -5000:80
    environment:
      - VUE_APP_API_ENDPOINT=http://backend:4001/api
    depends_on:
      - backend