version: "3.9"
networks:
  bridge-network:
    driver: bridge
services:
  backend:
    build: ./server
    ports:
      - 4001:4001
    networks:
      - bridge-network

  frontend:
    build: ./spa
    ports:
      - 5000:80
    networks:
      - bridge-network
    depends_on:
      - backend